name: Deploy Docker Image to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull Docker Image
        run: ssh -o StrictHostKeyChecking=no root@139.84.171.164 'docker pull daman830/foodifyi'

      - name: Run Docker Container
        run: ssh -o StrictHostKeyChecking=no root@<your_server_ip> 'docker run -d --name my-container -p 4000:4000 daman830/foodifyi'
